name: urvandeniss_s_1
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_datepicker: ^25.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
